apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-learning-platform.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devops-learning-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
  - name: http
    port: {{ .Values.service.backend.port }}
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "devops-learning-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-learning-platform.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devops-learning-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
  - name: http
    port: {{ .Values.service.frontend.port }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "devops-learning-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
