version: '3.8'

services:
  backend:
    build:
      context: ../..
      dockerfile: devops/docker/Dockerfile.backend
    container_name: devops-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - devops-network
    restart: unless-stopped

  frontend:
    build:
      context: ../..
      dockerfile: devops/docker/Dockerfile.frontend
    container_name: devops-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - devops-network
    restart: unless-stopped

networks:
  devops-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
