global:
  image:
    tag: "v2.7.6"

configs:
  params:
    server.insecure: true
    server.disable.auth: false
    server.enable.proxy.extension: true

server:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - argocd.devops-learning.local
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.devops-learning.local

  config:
    url: https://argocd.devops-learning.local
    application.instanceLabelKey: argocd.argoproj.io/instance
    
    repositories: |
      - type: git
        url: https://github.com/davmano/devops-learning-app
        name: devops-learning-app
        
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.health ~= nil then
          hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
        end
      end
      return hs

  rbacConfig:
    policy.default: role:readonly
    policy.csv: |
      p, role:admin, applications, *, */*, allow
      p, role:admin, clusters, *, *, allow
      p, role:admin, repositories, *, *, allow
      p, role:admin, logs, get, *, allow
      p, role:admin, exec, create, */*, allow
      
      p, role:developer, applications, get, */*, allow
      p, role:developer, applications, sync, */*, allow
      p, role:developer, logs, get, */*, allow
      
      g, devops-team, role:admin
      g, developers, role:developer

dex:
  enabled: false

notifications:
  enabled: true
  argocdUrl: https://argocd.devops-learning.local

applicationSet:
  enabled: true

repoServer:
  replicas: 2
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 256Mi

controller:
  replicas: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
