apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  devops.server: |
    devops-learning.local:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
            max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
        hosts {
            192.168.1.100 devops-learning.local
            fallthrough
        }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-dns-config
  namespace: kube-system
data:
  hosts: |
    127.0.0.1 localhost
    ::1 localhost
    
    192.168.1.100 devops-learning.local
    192.168.1.100 api.devops-learning.local
    192.168.1.100 grafana.devops-learning.local
    192.168.1.100 prometheus.devops-learning.local
    192.168.1.100 argocd.devops-learning.local
